import ipywidgets as widgets
from IPython.display import display, clear_output

word_data = [
['latter', '後者', 'Among the two choices, I prefer the latter.'],
['erosion', '浸食、侵食', 'Erosion can cause damage to the environment.'],
['nutrient', '栄養素', 'Nutrients such as vitamins are essential for good health.'],
['compose', '作曲する、構成する', 'The musician will compose a new symphony.'],
['secure', '確保する', 'She secured a ticket for the show.'],
['accommodate', '収容する、宿泊させる、融通してやる', 'The conference room can accommodate up to 100 attendees.'],
['secretary', '秘書', 'He works as a legal secretary at the law firm.'],
['brilliant', '輝かしい、素晴らしい', 'She saw a brilliant star in the sky.'],
['substance', '物質', 'Researchers discovered a new substance.'],
['asset', '資産', 'The company’s most valuable asset is its employees.'],
['compound', '混ぜ合わせる', 'The chemist mixed two compounds to create a new substance.'],
['sibling', '兄弟姉妹', 'Her siblings are all brilliant and filled with kindness.'],
['encourage', '励ます、促す', 'He always encourages me to pursue my dreams.'],
['confirm', '確認する', 'Please confirm the time of the meeting.'],
['riddle', 'なぞなぞ', 'I wonder who can solve such a difficult riddle.'],
['intellectual', '知的な', 'His intellectual curiosity made him pursue higher education.'],
['beaks', 'くちばし', 'I like your beaks.'],
['dull', '退屈な、鈍い', 'No one likes a dull presentation.'],
['right person', '適任者、適切な人', 'Finding the right person is essential for a company’s success.'],
['immense', '巨大な', 'Her family inherited an immense fortune.'],
['admire', '賞賛する', 'I admire the dedication of the volunteers.'],
['tumor', '腫瘍', 'The surgeon removed the entire tumor in an instant.'],
['ironic', '皮肉な', 'It is ironic that the fire station burned down.'],
['extra-curricular', '学校の授業以外の、課外の', 'Extra-curricular activities help you develop new skills.'],
['irrigation', '灌漑', 'Irrigation is the process of providing water to crops.'],
['freshwater', '淡水', 'Unlike seawater, freshwater contains little salt.'],
['nursery', '託児所', 'Children learn social skills in this nursery.'],
['missing', '見つからない、行方不明の', 'That’s the missing piece of the puzzle.'],
['moisture', '水分、湿気', 'A lack of moisture in the air reduced the amount of rain.'],
['sidewalk', '歩道', 'The children rode their bikes on the sidewalk to avoid traffic.'],
['well-off', '裕福な', 'Well-off families have better access to healthcare.'],
['recreation', 'レクリエーション、娯楽', 'Sports are popular forms of recreation.'],
['landowner', '土地所有者', 'Becoming a farm landowner requires knowledge of agriculture.'],
['dim', '暗い', 'The dim lighting made it difficult to read.'],
['glacier', '氷河', 'Glaciers are mostly made from freshwater.'],
['habitat', '生息地', 'More wetland habitats are needed for the wildlife.'],
['irrelevant', '関係のない', 'The comment was irrelevant to the topic.'],
['conscious', '気付いている、意識的な', 'I was conscious that something was missing.'],
['significance', '意味、重要性', 'I failed to understand the significance of his remarks.'],
['specifically', '詳細に言うと', 'Specifically, the agenda was about national defense.'],
['attorney', '弁護士', 'The attorney quoted a line from a law book.'],
['revenue', '収益、歳入', 'The company’s revenue increased after the new product launch.'],
['somewhat', '幾分は', 'This project is somewhat more difficult than I thought it would be.'],
['plastic', '柔軟な', 'One feature of the brain is that it’s highly plastic.'],
['vital', '不可欠な', 'Science is a vital part of the school curriculum.'],
['serve', '提供する、仕える', 'The restaurant strives to serve quality food.'],
['inventory', '在庫', 'All the inventory in the warehouse will be cleared.'],
['obey', '従う', 'It is important to obey the laws and rules.'],
['false', '誤った', 'The theory that the Earth is flat is false.'],
['contamination', '汚染', 'Water contamination can cause illness.'],
['whole', '全体的な', 'Safety is crucial during the whole process.'],
['yawn', 'あくびをする', 'I was yawning many times unconsciously.'],
['magnitude', '大きさ、巨大さ', 'This equipment measures the magnitude of quakes accurately.'],
['alter', '変える', 'Small changes can alter the taste of a meal.'],
['fur', '毛皮', 'Bad weather caused the cat’s fur to become wet.'],
['obvious', '明らかな', 'It is obvious this information is false.'],
['wool', '羊毛', 'Wool is a fiber that comes from animals, while cotton comes from plants.'],
['historian', '歴史家', 'The historian focused on European modernism.'],
['pale', '青白い', 'She grew pale with fear.'],
['prevention', '予防、防止', 'Prevention is key when it comes to health.'],
['amphibian', '両生類', 'Endangered amphibians are the subject of a recent study.'],
['whereas', '一方で、〜であるのに対して', 'Some people seek wealth, whereas others seek happiness.'],
['vegetation', '草木', 'The desert has very little vegetation.'],
['scold', '叱る', 'He softly scolded his son so as not to hurt him.'],
['grammatical', '文法的な', 'Correct grammatical errors before submitting your essay.'],
['indeed', '実に、本当に', 'Indeed, the duo looked nervous and pale.'],
['embarrass', '恥ずかしくさせる', 'He was embarrassed by his mistake.'],
['arise', '発生する、生じる', 'Financial problems continued to arise.'],
['hemisphere', '半球', 'Many migratory birds travel between hemispheres.'],
['beneath', '~の下に', "Beneath the earth's crust is the mantle."],
['examine', '調べる', 'It is important to examine all evidence.'],
['offend', '怒らせる、罪を犯す', "The comedian's jokes offended some people."],
['reddish', '赤みがかった', 'The moon had a reddish hue in the dark sky.'],
['cultivation', '栽培、育成', 'Mayans were skilled in agriculture and cultivation.'],
['fertilizer', '肥料', 'Fertilizer is used to enrich the soil.'],
['droplet', '小さなしずく', 'With a single droplet of red colored dye, the water turned pink.'],
['Arctic', '北極', 'The Arctic is home to many unique animal species.'],
['aisle', '通路', 'I prefer an aisle seat.'],
['evolve', '進化する', 'Plants and animals evolve over time.'],
['verify', '確認する、認証する', 'Verify your email address to create a new account.'],
['settle', '住み着く', 'We always thought about leaving the city and settling in the country.'],
['pleasant', '快活な、快適な', 'His personality is pleasant and welcoming.'],
['bulletin', '掲示、公報', 'The bulletin board displayed important announcements.'],
['altogether', '全体で、完全に', 'There were 15 participants altogether.'],
['bend', '曲げる', 'Don’t bend the envelope.'],
['hunter-gatherer', '狩猟採集民', 'In the beginning, the hunter-gatherer diet was vegan.'],
['civilian', '民間人、市民', 'It’s hard to identify civilians in a guerrilla war.'],
['groundwater', '地下水', 'The properties of soil affect groundwater movement.'],
['embarrassed', '恥ずかしい', 'She was embarrassed when she realized she had made a mistake.'],
['profitable', '利益性のある', 'Not all stock investments are profitable.'],
['dealer', '販売業者', 'The drug dealer was arrested and charged with multiple offenses.'],
['revolutionary', '革命的な', 'Wells are a revolutionary invention to utilize groundwater.'],
['inevitable', '不可避の', 'Rejection from the partner was inevitable.'],
['circular', '円形の', 'Her home had a circular staircase.'],
['commence', '始める', 'The ceremony will commence at 2 PM sharp.'],
['patent', '特許', 'Unfortunately, our patent application was rejected.'],
['flood', '洪水', 'Reddish soil covered the entire flat field after the flood.'],
['custom', '税関(-s)、習慣', 'We went through customs without any difficulty.'],
['ease', '楽にする', 'Taking deep breaths helps ease stress.'],
['oval', '楕円形', 'In the middle of the room was an oval-shaped table.'],
['grateful', '感謝している', 'I am grateful for the support of my family and friends.'],
['plentiful', '豊富な', 'Plentiful rainfall helps crops grow.'],
['prehistoric', '有史以前の、先史の', 'Prehistoric art often depicts animals and human figures.'],
['phenomenon', '現象', 'The Northern Lights are a natural phenomenon seen in the Arctic Circle.'],
['blow', '打撃', 'He received a massive blow to the head and suffered memory loss.'],
['hence', 'それゆえに', 'The introduction is unclear; hence, it needs to be rewritten.'],
['wheat', '小麦', 'Some say wheat allergies are caused by pesticides.'],
['emerge', '現れる', 'A new species of bird has emerged in the rainforest.'],
['differ', '異なる', 'Her parents differ in their approach to discipline.'],
['landscape', '風景、景観', 'Wind can change the landscape dramatically.'],
['mountain range', '山脈', 'It is quite rare to see snowfall on the desert mountain range.'],
['victim', '犠牲者', 'Support systems for victims need improvement.'],
['coastal', '沿岸の', 'Many coastal communities rely on fishing.'],
['manufacturer', '製造業者', 'Automation technology benefits many manufacturers.'],
['wealth', '富', 'Wealth inequality is a growing issue in many countries.'],
['broad', '広い', 'She had a broad view of the city from the top floor.'],
['invoice', '請求書', 'She sent the invoice to the vendor yesterday.'],
['violent', '暴力的な', 'Usually, he is not a violent person.'],
['foolish', '愚かな', 'It was foolish of me to use such violent words.'],
['conduct', '行う', 'Scientists must conduct experiments carefully and accurately.'],
['millennium', '千年', 'People celebrated the beginning of the new millennium.'],
['dictator', '独裁者', 'Dictators eventually face popular resistance.'],
['venture', 'ベンチャー事業', 'Starting a new venture is exciting.'],
['crust', '地殻', 'The crust of the Earth is made up of solid rock.'],
['drought', '干ばつ', 'Drought management requires water conservation.'],
['boldly', '大胆に、ずうずうしく', 'Colonists boldly explored unknown land.'],
['vivid', '鮮やかな', 'He gave a vivid description of his vacation.'],
['toe', 'つま先', 'I stubbed my toe on the corner of the table and it hurt.'],
['poet', '詩人', 'Emily Dickinson is an American poet, who wrote about nature and death.'],
['daydream', '空想する', 'Sometimes it’s nice to daydream and let your mind wander.'],
['preserve', '保存する', 'State laws help preserve our natural resources.'],
['compete', '競争する、競う', 'Athletes compete against each other to win the game.'],
['lid', 'ふた', 'Leaving a water bottle with a loose lid in a bag can be catastrophic.'],
['grain', '穀物、ひと粒', 'We have sufficient grain storage for drought seasons.'],
['astronaut', '宇宙飛行士', 'The astronaut experiences weightlessness in space.'],
['seller', '売り手', 'A skilled seller maximizes customer satisfaction.'],
['migrate', '移動する、渡る', 'Birds migrate south for the winter.'],
['fishery', '漁業', 'The current fishery will change the distribution patterns of fish.'],
['sail', '帆', 'Boats use sails to catch the wind and move forward.'],
['contradictory', '矛盾する', 'The contradictory evidence made it difficult to draw a conclusion.'],
['marine', '海の、海洋の', 'Marine life is diverse and fascinating.'],
['pretend', 'ふりをする', 'The merchant pretended that he lacked knowledge of trading.'],
['similarly', '同様に', 'Similarly, levers are used to lift heavy objects.'],
['generous', '寛大な', 'The TA was generous, always willing to help students.'],
['telescope', '望遠鏡', 'Using a telescope, the shooting stars were seen more vividly.'],
['nearby', '近くの', 'There was a fire in a nearby building.'],
['thickness', '厚さ', 'The cost is determined by the length and thickness of the wood.'],
['occasionally', '時々', 'People occasionally prefer digital communication.'],
['sue', '告訴する', 'The doctor who performed an unnecessary operation was sued.'],
['steady', '不変の、ぐらつかない', 'Some cosmologists insisted the universe was steady.'],
['bold', '大胆な', 'It was a bold move.'],
['reef', '礁', 'Coral reefs are dying out.'],
['interestingly', '興味深いことに', 'Interestingly, many dogs cannot distinguish between red and green.'],
['dizzy', 'めまいがする', 'She felt dizzy and sat down.'],
['verification', '確認、認証', 'Verification of your identity is necessary for security reasons.'],
['poverty', '貧困', 'Poverty has been a significant social problem.'],
['viewer', '視聴者', 'Every year, the awards show attracts millions of viewers.'],
['meanwhile', 'その間に', 'Meanwhile, the battalion crossed the Rubicon River.'],
['forestry', '林業、山林管理', 'Forestry provides continuous economic benefits.'],
['slope', '斜面', 'The slope is too steep and not suitable for agriculture.'],
['ensure', '保証する', 'The Energy Act does not ensure sustainable development.'],
['envy', 'ねたみ', 'The queen felt envy towards her friend’s success.'],
['cheerfully', '快活に、元気よく', 'The children were playing cheerfully in the park.'],
['rough', '粗い', 'The statue had a rough surface.'],
['roughly', 'おおよそ', 'Roughly one-third of the Earth’s surface is covered by land.'],
['tremendously', '非常に', 'Technology has improved our lives tremendously.'],
['practitioner', '開業医、実践者', 'She went from being a lawyer to a medical practitioner.'],
['continuously', '連続して', 'I plan to study continuously and take advantage of all opportunities.'],
['mature', '成熟する', 'Students matured into scholars.'],
['persuade', '説得する、納得させる', 'Council members persuaded the chairman to think twice.'],
['inappropriate', '不適切な', 'His behavior during the meeting was inappropriate.'],
['nationality', '国籍', 'Japan does not allow dual nationality.'],
['excess', '過剰', 'The party had an excess of food.'],
['radius', '半径', 'The radius of our solar system is 1.6 light years and that of our galaxy is 58,000.'],
['guilty', '有罪の', 'The defendant was found guilty of the crime.'],
['personnel', '人員', 'The personnel department handles hiring and benefits.'],
['chick', 'ひよこ', 'The chick hatched from the egg and began to chirp.'],
['secondary', '中等の、二次的な', 'High school is considered secondary education.'],
['admission', '入場、入学', 'Admission to the museum is free with a student ID.'],
['pesticide', '農薬', 'Organic farming avoids the use of synthetic pesticides.'],
['convey', '伝える', 'Facial expressions convey emotions.'],
['mud', '泥', 'A teaspoon of mud contains one billion bacteria.'],
['nutrition', '栄養摂取、栄養', 'Good nutrition is important for maintaining good health.'],
['firmly', '堅く', 'Thus, I firmly believe that cooperation is more important.'],
['stimulate', '刺激する', 'Exercise can stimulate the brain.'],
['interpretation', '解釈', 'The interpretation the author provided does not make sense.'],
['inhabit', '住む、居住する', 'Many species of animals inhabit the rainforest.'],
['betray', '裏切る', 'In the end, the dictator was betrayed and stabbed.'],
['landslide', '地滑り', 'Excessive rain caused sudden landslides.'],
['ongoing', '進行中の', 'Ongoing research seeks potential treatments for depression.'],
['quarrel', '口論する', 'They are always quarreling about money.'],
['meteorite', '隕石', 'There is always a chance that a meteorite will hit the Earth.'],
['valuable', '価値のある', 'Clean air is a valuable natural resource.'],
['underneath', '~の下に', 'Grass and twigs were laid underneath the nest.'],
['sanitation', '衛生', 'Proper sanitation is important to prevent the spread of diseases.'],
['twisted', 'ねじれた', 'Twisted nanofibers have tremendous applications.'],
['toward', '~に向かって', 'Efforts toward peace have been largely unsuccessful.'],
['keen', '鋭い、強烈な', 'The RA demonstrated her keen observation skills.'],
['recipient', '受取人', 'The organ recipient is gradually recovering.'],
['infectious', '伝染性の', 'Infectious diseases were rare among nomads.'],
['commodity', '商品', 'At times, commodity prices can rise sharply.'],
['isolated', '隔離された', 'The workshop was in an isolated area of the woods.'],
['regional', '地域の', 'The regional microclimate here is suitable for this tree.'],
['deepen', '深める', 'Officials deepened their relationships through communication.'],
['favorable', '望ましい', 'Favorable conditions are needed for plant growth.'],
['identical', 'まったく同じ', 'These two jellyfish appear identical, but they are different.'],
['generally', '一般的には、大抵は', 'Generally, students are required to attend all classes.'],
['asteroid', '小惑星', 'An asteroid is a small rocky object that orbits the sun.'],
['fluid', '流体', 'Resin, tar, and pitch are all sticky fluids.'],
['dig', '掘る', 'Squirrels dig holes here and there.'],
['hectic', '大忙しの', 'The professor had a hectic schedule throughout the semester.'],
['tackle', '取り組む', 'The UN is tackling the issue of racism.'],
['poorly', '不十分に、下手に', 'The experiment was poorly designed.'],
['nerve', '神経', 'Usually nerve cells don’t divide.'],
['throat', '喉', 'Multiple nerves run around the throat.'],
['goose bump', '鳥肌', 'Goose bumps form as the skin tries to minimize heat radiation.'],
['veteran', '退役軍人、ベテラン', 'A veteran is a person who has served in the military.'],
['communist', '共産主義者', 'In communist ideology, the state owns everything.'],
['expenditure', '支出', 'The Vikings used the silver coins for their expenditures.'],
['distant', '遠い', 'In the distant past, the earth was covered with ice.'],
['fascinating', '魅力的な', 'The astronomical show was just fascinating.'],
['loose', '緩い', 'The screws are loose and need to be tightened.']
]
def ask_questions(word_data):
    for i, (word, hint, example) in enumerate(word_data):
        print(f"\nQuestion {i+1}: Do you know the meaning of '{word}'?")
        print(f"Hint: {example}")

        while True:
            answer = input("Yes or No (y/n): ").lower()
            if answer in ('y', 'yes'):
                print(f"{word}: Correct!")
                break
            elif answer in ('n', 'no'):
                print(f"{word}: Incorrect. The answer is: {hint} - {example}")
                break
            else:
                print("Invalid input. Please enter 'y' or 'n'.")


ask_questions(word_data)
